package org.oreon.core.scenegraph

enum class NodeComponentType {
    MAIN_RENDERINFO,
    WIREFRAME_RENDERINFO,
    SHADOW_RENDERINFO,
    REFLECTION_RENDERINFO,
    REFRACTION_RENDERINFO,
    MATERIAL0,
    MATERIAL1,
    MATERIALS,
    LIGHT,
    BUFFERS,
    MESH_DATA,
    SHADER_RESOURCE,
    CONFIGURATION
}